from turtle import *
   
   
def main():
    reset()
    radius=120
    width(5)
    #big circle
    color("#DD4814", "#DD4814") 
    begin_fill()
    circle(radius/1.2, 360)
    color("#DD4814","#DD4814")
    end_fill()
    #set small circle
    up()
    right(90)
    backward(radius/2)
    left(90)
    circle(radius/3.,-30)
    down()
    #1/3circle
    circle(radius/3., 120)
    begin_fill()
    up()
    circle(radius/3., -120)
    right(90)
    down()
    forward(radius/6.)
    left(90)
    circle(radius/2., 120)
    left(90)
    forward(radius/6.)
    color("#DD4814","white")
    end_fill()
    up()
    backward(radius/6.)
    right(90)
    circle(radius/2.,-70)
    right(90)
    forward(5)
    down()
    begin_fill()
    circle (16,360)
    color("#DD4814","white")
    end_fill()
    up()
    backward(5)
    left(90)
    circle(radius/2., 70)
    left(90)
    forward(radius/6.)
    down()
    
    #2/3circle
    right(90)
    up()
    down()    
    circle(radius/3., 120)
    begin_fill()
    up()
    circle(radius/3., -120)
    right(90)
    down()
    forward(radius/6.)
    left(90)
    circle(radius/2., 120)
    left(90)
    forward(radius/6.)
    color("#DD4814","white")
    end_fill()
    up()
    backward(radius/6.)
    right(90)
    circle(radius/2.,-70)
    right(90)
    forward(5)
    down()
    begin_fill()
    circle (16,360)
    color("#DD4814","white")
    end_fill()
    up()
    backward(5)
    left(90)
    circle(radius/2., 70)
    left(90)
    forward(radius/6.)
    down()
    
    #3/3circle
    right(90)
    up()
    down()    
    circle(radius/3., 120)
    begin_fill()
    up()
    circle(radius/3., -120)
    right(90)
    down()
    forward(radius/6.)
    left(90)
    circle(radius/2., 120)
    left(90)
    forward(radius/6.)
    color("#DD4814","white")
    end_fill()
    up()
    backward(radius/6.)
    right(90)
    circle(radius/2.,-70)
    right(90)
    forward(5)
    down()
    begin_fill()
    circle (16,360)
    color("#DD4814","white")
    end_fill()
    up()
    backward(5)
    left(90)
    circle(radius/2., 70)
    left(90)
    forward(radius/6.)
    down()
    
    ht()
    return "Done!"

if __name__ == '__main__':
    main()
    mainloop()

